//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplicationFootballplayer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.Position = new HashSet<Position>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Firstname { get; set; }
        public string Printname { get; set; }
        public System.DateTime Birthdate { get; set; }
        public string Primary_Nationality { get; set; }
        public long Market_Value { get; set; }
        public bool Injured { get; set; }
    
        public virtual ICollection<Position> Position { get; set; }
    }
}
